version: 2.1
jobs:
  build:
    docker:
      - image: lpodkalicki/stm32-toolchain:latest 
    resource_class: small
    steps:
      - checkout
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: make
          command: |
            ls
            make
#      - save_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#          paths:
#            - "venv"
      - run:
          name: products
          command: |
            ls build/
            rm build/*.{o,d,lst}
      - store_artifacts:
          path: build/
          destination: products`

#  submodule:
#    docker:
#      - image: cimg/python:3.10.1
#    resource_class: small
#    steps:
#      - checkout
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#      - run:
#          command: |
#            python3 -m venv venv
#            . venv/bin/activate
#            pip install -r requirements.txt
#            pip install pytest
#            git submodule update --init 
#      - save_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#          paths:
#            - "venv"
#      - run:
#          name: Running tests
#          command: |
#            . venv/bin/activate
#            python3 -m pytest | tee test-reports/pytest.log
#      - store_artifacts:
#          path: test-reports/
#          destination: python_app
workflows:
  version: 2
  workflow:
    jobs:
    - build
#    - pytest
#    - submodule
  

